### ISSUE TITLE
Hooks?

### ISSUE THREAD

**Issue by fluxxu** [Masterminds/structable#2]
Do you think hooks fit in structable's design?
For example,
I have a struct

``` go
type Object struct {
    Id int `stbl:"id, PRIMARY_KEY, AUTO_INCREMENT"`
    PropsJSON string `stbl:"props_json"`
    CreatedAt time.Time `stbl:"create_at"`
    UpdatedAt time.Time `stbl:"updated_at"`

    Props map[string]string
}
```

I want CreateAt and UpdatedAt updated and PropsJSON <=> Props get transformed automatically.
My first thought is that if structable supports Hooks I can write following methods:

``` go
// called before Insert
func (this *Object) BeforeInsert() {
    this.CreatedAt = time.Now()
}

// called before Update
func (this *Object) BeforeUpdate() {
    this.UpdatedAt = time.Now()
}

// called before Insert and Update
func (this *Object) BeforeSave() {
    _, this.ProsJSON = json.Marshal(&this.Props)
}

// called after Load
func (this *Object) AfterLoad() {
    json.Unmarshal([]byte(this.PropsJSON), &this.Props)
}
```

Do you think this is a good idea? 

Thanks!

**Comment by technosophos** [comment]
That is an interesting idea. I could see it being very useful.
Are you thinking we'd implement it with interfaces? Maybe something like:
```go
type BeforeInserter interface {
    func BeforeInsert()
}
```
Then I guess the save function could easily type-check `this` and execute `BeforeInsert` when appropriate.
